# Generated by Django 5.2.5 on 2025-11-09 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalles_pedidos',
            name='id_detalle',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='fecha_termino',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='margen_ganancia',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_critico',
        ),
        migrations.AddField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='rut',
            field=models.CharField(default=1111111111, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalles_pedidos',
            name='email_usuario',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='detalles_pedidos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_pedidos/'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='apellido',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalles_pedidos',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pedidos'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='contacto_distribuidor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='distribuidor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
