# Generated by Django 5.2.5 on 2025-11-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_detalles_pedidos_id_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
