# Generated by Django 5.2.5 on 2025-11-09 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pedidos_fecha_entrega_pedidos_fecha_termino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalles_pedidos',
            name='id',
        ),
        migrations.AddField(
            model_name='detalles_pedidos',
            name='id_detalle',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detalles_pedidos',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detalles_pedidos',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='main.pedidos'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
